name: delivery_ui
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  pinput: ^3.0.1
  sliver_tools: ^0.2.12
  rename: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  country_code_picker: ^3.0.0
  intl_phone_field: ^3.2.0
  date_picker_plus: ^3.0.2
  dotted_border: ^2.1.0
  flutter_rounded_date_picker: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21
